postgres:
  driver: postgresql+psycopg2
  user: dev_user
  password: dev_user
  database: edu

flask:
  secret: xede134da2eqDQWD@12ewe


logging:
  version: 1
  disable_existing_loggers: True
  formatters:
    shortened:
      format: "%(message)s"
    std:
      format: "%(levelname)s %(name)s: %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: std
      stream: ext://sys.stdout
  loggers:
    default:
      level: INFO
      handlers: [console]